### PR TITLE
fixed issues with searchbar

### PR DESCRIPTION
**Pull request by julie-var**
Adding Searchbar to navigation bar

### CODE REVIEW

**Comment by RmataM7** [comment]
Could you incorporate a _search_ function that does a simple search of the items list on the home page please. Thank you

**Review by RmataM7 — CHANGES_REQUESTED** [review]
Add search functionality

**Comment by IamSLopez** [comment]
I've updated the search bar. It should be ready to go.

**Comment by RmataM7** [comment]
Looks great! thank you

**Pull request merged**
